slug: where-is-web-assembly
publish_date: 2022-07-08
tags: [article, web-assembly]

title: Where is Web Assembly?
subtitle: Where is Web Assembly and what can we do to get it out of the lab?
description: An article speculating on the future of web technologies

image: assets/hero.png
image_alt: Cartoon depicting people waiting for an answer to "I will show you how to write web apps in any language"
