slug: the-case-for-a-sandboxed-script
publish_date: 2022-07-18
tags: [html, security, web, new-frontiers]

title: A case for a sandbox-able <script> tag
subtitle: Enhancing security on the web

image: assets/hero.png
image_alt: Picture of a children's sand pit
