slug: the-case-for-a-sandboxed-script-tag
publish_date: 2022-07-18
tags: [article, web, html, security, privacy]

title: The Case For a Sandboxed Script Tag
subtitle: Enhancing security on the web
description: An article examining the utility of allowing script tags to be sandboxable

image: assets/hero.png
image_alt: Picture of a children's sand pit
