slug: solid-typescript
publish_date: 2019-03-12
tags: [typescript, programming, software-design]

title: SOLID TypeScript
subtitle: Less about frameworks, more about engineering

image: assets/hero.png
image_alt: Picture of pillars with SOLID written on top
