title: SOLID TypeScript
subtitle: Less about frameworks, more about engineering
description: Less about frameworks, more about engineering
image: assets/pilars.png
image_alt: Picture of pillars with SOLID written on top
publish_date: 2022-11-09
tags:
  - basic
  - programming
