slug: hosting-an-spa-on-s3
publish_date: 2019-04-06
tags: [tutorial, video, web development, aws]

title: Hosting a Single Page Application on Amazon's AWS S3
subtitle: The best part is it's practically free!
description: A tutorial on using AWS S3 to host a Single Page Application

image: assets/hero.png
video_youtube: _XuQnZzuLJA
