slug: go-and-angular
publish_date: 2019-03-19
tags: [tutorial, video, golang, go, web development]

title: Building a Web Application with Go and Angular
subtitle: Wielding this dynamic duo has never been easier
description: A tutorial on creating a web application using Go and Angular

image: assets/hero.png
video_youtube: pHRHJCYBqxw
