slug: installing-debian-and-gnome-41
publish_date: 2022-01-06
tags: [tutorial, video, linux, gnome]

title: Installing Gnome 4x on Debian Sid
subtitle: Using vanilla Gnome with a vanilla Debian based Linux distro
description: A tutorial on installing Gnome 4x on Debian Sid

image: assets/hero.png
video_youtube: xpf4_2cZ2Mw
