slug: an-update-on-go-and-generics
publish_date: 2019-03-12
tags: [article, golang, generics, go, update]

title: An Update on Go and Generics in 2019
subtitle: Technically it's called “Parametric Polymorphism” but that's fine
description: 

image: assets/hero.webp
image_alt: Picture of a children's sand pit
