defaultCacheControl: 'max-age=86400, public'
rules:
  # /etag.json
  - regex: ^\/etag\.json$
    cacheControl: 'max-age=0'

  # /**/index.html, /**/index.css, /**/index.js, /**/index.json
  - regex: ^(\/)(.*)(index\.(css|js|html|json))$
    cacheControl: 'max-age=0'

  # /**/*.html, /**/*.css, /**/*.js
  - regex: ^(\/)(.*)(\.css|js|html|json)$
    cacheControl: 'max-age=31536000, immutable, public'

  # /assets/**/*
  - regex: ^(\/)(assets\/)(.*)$
    cacheControl: 'max-age=31536000, public'
