name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "Install Nodejs" 
      run: bash .github/workflows/install-nodejs.bash

    - name: Upload HTML to AWS
      run: |
        set -e
        
        node -v

        export AWS_DEFAULT_OUTPUT="yaml"
        export AWS_PAGER=
        export AWS_EC2_METADATA_DISABLED=true

        npm install
        env PROD=true URL="https://davidalsh.com" npm run build
        env DRY=false npm run publish
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
